### ISSUE TITLE
нужна помощь

### ISSUE THREAD

**Issue by Roman-code37** [Roman-code37/02.kfc#1]
@coursar и у меня снова проблема. не могу понять, почему выходят ошибки
![Снимок экрана (1)](https://user-images.githubusercontent.com/55130715/65698969-083d8600-e086-11e9-99fc-513aed60353d.png)
![Снимок экрана (2)](https://user-images.githubusercontent.com/55130715/65698970-08d61c80-e086-11e9-863d-acd55cb59dae.png)

**Comment by coursar** [comment]
Потому что классы пишутся с большой буквы:
```java
Burger chefBurger = new Burger();
...
```
